---  
- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Disable X-Pack Security in Elasticsearch
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^xpack.security.enabled:'
    line: 'xpack.security.enabled: false'

- name: Start Elasticsearch service
  systemd:
    name: elasticsearch
    state: started

- name: Enable Elasticsearch service at boot
  systemd:
    name: elasticsearch
    enabled: yes