---
- name: Install Logstash
  apt:
    name: logstash
    state: present
- name: Configure the logstash
  copy:
    src: ../files/logstash-default.conf
    dest: /etc/logstash/conf.d/

# - name: Copy files to remote
#   copy:
#     src: /path/to/local/file1
#     dest: /path/to/remote/destination/
#   # Use a second task for the second file
# - name: Copy another file to remote
#   copy:
#     src: /path/to/local/file2
#     dest: /path/to/remote/destination/

- name: Start Logstash service
  systemd:
    name: logstash
    state: started

- name: Enable Logstash service at boot
  systemd:
    name: logstash
    enabled: yes