#cloud-config
package_update: true

users:
  - name: <remote_name>
    uid: 1001
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
    - <public key>
